apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: zarf-pepr
agents: 1
subnet: "172.28.0.0/16"
hostAliases:
  - ip: 172.28.0.2
    hostnames:
      - keycloak.bigbang.dev
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable=servicelb
        nodeFilters:
          - server:*
volumes:
  - volume: /etc/machine-id:/etc/machine-id
    nodeFilters:
      - server:0
      - agent:*