addons:
  authservice:
    enabled: true

    chains:
      podinfo:
        callback_uri: https://podinfo.bigbang.dev/login
        client_id: podinfo
        client_secret: 2mMLbBB2V7ngoGOY0N6fP0i47f68eDNP
        logout_path: /logout
        match:
          header: :authority
          prefix: podinfo.bigbang.dev

  keycloak:
    enabled: true
    ingress:
      gateway: "public"

monitoring:
  enabled: true
    
  values:
    networkPolicies:
      enabled: true
    grafana:
      persistence:
        enabled: false
    prometheus:
      prometheusSpec:
        storageSpec: null

istio:
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer" 
      kubernetesResourceSpec:
        service:
          loadBalancerIP: 172.28.0.2
  gateways:
    passthrough:
      ingressGateway: public-ingressgateway
      hosts:
        - "keycloak.{{ .Values.domain }}"
      tls:
        mode: "PASSTHROUGH"

neuvector:
  enabled: true
  values:
    k3s:
      enabled: true
      runtimePath: /run/k3s/containerd/containerd.sock

    containerd:
      enabled: false

kyvernoPolicies:
  enabled: true
  values:
    policies:
      disallow-host-namespaces:
        exclude:
          any:
          # Istio does not inject itself
          - resources:
              namespaces:
              - metallb-system
      restrict-host-path-mount:
        validationFailureAction: audit
        parameters:
          allow:
           - "###ZARF_VAR_HOST_PATH###"
        exclude:
          any:
          # Istio does not inject itself
          - resources:
              namespaces:
              - monitoring
      restrict-host-path-mount-pv:
        validationFailureAction: audit
        exclude:
          any:
          # Istio does not inject itself
          - resources:
              namespaces:
              - monitoring
        parameters:
          allow:
           - "###ZARF_VAR_HOST_PATH###"
      restrict-host-path-write:
        parameters:
          allow:
           - "###ZARF_VAR_HOST_PATH###"
      restrict-image-registries:
        exclude:
          any:
          # Istio does not inject itself
          - resources:
              namespaces:
              - metallb-system
      restrict-host-ports:
        exclude:
          any:
          # Istio does not inject itself
          - resources:
              namespaces:
              - metallb-system
    
