name          = "###ZARF_VAR_NAME###"
force_destroy = "###ZARF_VAR_LOKI_FORCE_DESTROY###"
disable_eks   = "###ZARF_VAR_DISABLE_EKS###"
create_irsa   = "###ZARF_VAR_CREATE_IRSA###"
#kms_key_arn   = "###ZARF_VAR_LOKI_KMS_KEY_ARN###"
