package:
  create:
    max_package_size: "1000000000"
  deploy:
    set:
      domain: bigbang.dev
      hosted_zone_id: "notarealzone"
      route53_role_arn: "arn:aws:iam::000000000000:role/eksctl-bigbang-dns-addon-iamserviceaccount-e-Role1-ABC123ABC123"
