domain: "###ZARF_VAR_ADMIN_DOMAIN###"

networkPolicies:
  enabled: true
  controlPlaneCidr: "0.0.0.0/0"
  nodeCidr: "0.0.0.0/0"
  vpcCidr: "0.0.0.0/0"

# Disable all Flux retry/rollback behavior
flux:
  upgrade:
    remediation:
      retries: 0
      remediateLastFailure: false
    cleanupOnFail: false
  interval: 1m

addons:
  velero:
    enabled: false
