apiVersion: "security.istio.io/v1beta1"
kind: PeerAuthentication
metadata:
  name: controller-neuvector
  namespace: neuvector
spec:
  selector:
    matchLabels:
      app: neuvector-controller-pod
  mtls:
    mode: STRICT
  portLevelMtls:
    "18300":
      mode: PERMISSIVE
