package:
  create:
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.7.1"
      # should line up with the flux version in the BB release, see https://repo1.dso.mil/big-bang/bigbang/-/blob/master/base/flux/gotk-components.yaml#L3
      flux_version: "2.0.1"
      terraform_version: "1.4.2"
      terraform_provider_aws_version: 4.59.0
      # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
      zarf_version: "v0.28.3"

  deploy:
    set:
      # -- Domain name for the EKS cluster
      domain: bigbang.dev
      # -- TLS key
      key_file: bigbang.dev.key
      # -- TLS cert
      cert_file: bigbang.dev.cert
      # -- Name of the EKS cluster
      name: "big-bang-aws"
      # -- Name of existing Terraform state bucket
      state_bucket_name: uds-dev-state-bucket
      # -- Key path to Terraform state file within the bucket
      state_key: tfstate/dev/uds-dev-state-bucket.tfstate
      # -- Name of DynamoDB table used for Terraform state locking
      state_dynamodb_table_name: uds-dev-state-dynamodb
      # -- AWS region
      region: us-west-2
      # -- Provision a private/internal load balancer for the admin ingress gateway, if false a public load balancer will be provisioned
      private_admin_lb: true
      # -- Provision a private/internal load balancer for the tenant ingress gateway, if false a public load balancer will be provisioned
      private_tenant_lb: true
      # -- VPC ID
      vpc_id: vpc-089e6f8e2dd1d8591
      # -- VPC CIDR block
      vpc_cidr: 192.168.0.0/16
      # -- Private subnet IDs for cluster as a comma-separated string
      private_subnets: subnet-089bba221efd8a2e2,subnet-08ce3b3da0a310d75,subnet-0b71abd76c74ea47a
      # -- Public subnet IDs for cluster as a comma-separated string
      public_subnets: subnet-04469f93c6f962949,subnet-04d87e6a555915c79,subnet-061e0c1827bd519b0
      # -- Allow public access to cluster
      cluster_endpoint_public_access: false
      # -- If set to true, force delete all resources on removal (i.e. loki S3 bucket, PVCs, etc)
      ephemeral: false
      # -- Bring your own kms key, if omitted a key will be created with an alias prefix of "<cluster name>-loki-"
      #loki_kms_key_arn: "arn:aws:kms:us-west-2:000000000000:key/mrk-0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a"
