apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
  namespace: flux-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 300m
              memory: 768Mi
            requests:
              cpu: 300m
              memory: 768Mi
