apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "###ZARF_VAR_CLUSTER_NAME###"
  region: us-west-2
  version: "1.29"
  tags:
    PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_NAME###"

# May want to look at this for testing
# privateCluster:
#   enabled: true

iam:
  withOIDC: true
  serviceRolePermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"

addons:
  - name: aws-ebs-csi-driver
    version: v1.32.0-eksbuild.1

    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
    permissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
    tags:
      PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_NAME###"

  - name: vpc-cni
    permissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
    tags:
      PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_NAME###"

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 3
    volumeSize: 150
    tags:
      PermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_NAME###"
    iam:
      instanceRolePermissionsBoundary: "###ZARF_VAR_PERMISSIONS_BOUNDARY_ARN###"
    ami: "###ZARF_VAR_AMI_ID###"
    amiFamily: AmazonLinux2
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh ###ZARF_VAR_CLUSTER_NAME### --container-runtime containerd
