apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "###ZARF_VAR_CLUSTER_NAME###"
  region: us-west-2
  version: "1.27"

# May want to look at this for testing
# privateCluster:
#   enabled: true

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    version: v1.25.0-eksbuild.1

    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy

managedNodeGroups:
  - name: ng-1
    instanceType: m5.2xlarge
    desiredCapacity: 3
    volumeSize: 150
