name: Lint Terraform

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      capability:
        type: string
        description: "The name of the capability to test"
        required: true
  # Triggered by pull-request-conditionals.yaml
  workflow_call:
    inputs:
      capability:
        type: string
        description: "The name of the capability to test"
        required: true

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init
        working-directory: ${{ inputs.capability }}

      - name: terraform validate
        run: terraform validate
        working-directory: ${{ inputs.capability }}

      - name: terraform fmt
        run: terraform fmt -recursive
        working-directory: ${{ inputs.capability }}

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact --recursive

  tfsec-scan:
    needs: [tflint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ github.token }}
          soft_fail: true

  regula:
    needs: [tflint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: List Directories
        run: ls -lsa

      - name: Scan with Regula
        uses: fugue/regula-action@v3.2.1
        with:
          input_path: ${{ inputs.capability }}
          input_type: tf
          severity: high