apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - podinfo-vs.yaml
  - client-create-secret.yaml
  - github.com/stefanprodan/podinfo/kustomize?ref=6.3.6
patches:
- target:
    kind: Deployment
    name: podinfo
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: podinfo
    spec:
      template:
        metadata:
          labels:
            protect: keycloak