package:
  create: 
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.1.0"
  deploy:
    set:
      domain: vp.bigbang.dev
      public_key_file: vp.bigbang.dev.key
      public_cert_file: vp.bigbang.dev.cert
      keycloak_key_file: vp.bigbang.dev.key
      keycloak_cert_file: vp.bigbang.dev.cert