application:
  name: keycloak
  createNamespace: ###ZARF_VAR_KEYCLOAK_CREATE_NAMESPACE###
  namespace: keycloak
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/keycloak.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/packages/keycloak versioning=loose registryUrl=https://repo1.dso.mil
    tag: 18.4.3-bb.2
  values: |
    ###ZARF_VAR_KEYCLOAK_VALUES###
  dependsOn:
    ###ZARF_VAR_KEYCLOAK_DEPENDS_ON###
