package:
  create:
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.34.0"
      # should line up with the flux version in the BB release, see https://repo1.dso.mil/big-bang/bigbang/-/blob/master/base/flux/gotk-components.yaml#L3
      flux_version: "2.3.0"
  deploy:
    set:
      # -- Domain name for the EKS cluster
      domain: "bigbang.dev"
      # -- TLS key
      key_file: "bigbang.dev.key"
      # -- TLS cert
      cert_file: "bigbang.dev.cert"
      # -- Name of the EKS cluster
      name: "big-bang-aws"
      # -- Provision a private/internal load balancer for the admin ingress gateway, if false a public load balancer will be provisioned
      private_admin_lb: "true"
      # -- Provision a private/internal load balancer for the tenant ingress gateway, if false a public load balancer will be provisioned
      private_tenant_lb: "true"
      # -- If set to true, delete PVs on removal
      ephemeral: "false"
      # -- AWS S3 bucket for use with Loki
      loki_s3_bucket: "big-bang-aws-loki-s3"
      # -- Region of the AWS S3 bucket for use with Loki
      loki_s3_aws_region: "us-west-2"
      # -- Role ARN of the AWS S3 bucket for use with Loki
      loki_s3_role_arn: "arn:aws:iam::000000000000:role/big-bang-aws-0a0a0a0-loki-logging-loki-irsa"
      # -- AWS S3 bucket for use with Velero
      velero_s3_bucket: "big-bang-aws-velero-s3"
      # -- Region of the AWS S3 bucket for use with Velero
      velero_s3_aws_region: "us-west-2"
      # -- Role ARN of the AWS S3 bucket for use with Velero
      velero_s3_role_arn: "arn:aws:iam::000000000000:role/big-bang-aws-0a0a0a0-velero-velero-velero-server-irsa"
