name: Get Latest DUBBD Package Version
description: Fetches the latest version of the specified DUBBD package

inputs:
  github-token:
    description: GitHub token to authenticate to the GitHub REST API
    required: true
  package-name:
    description: Name of the DUBBD package
    required: true

outputs:
  latest-dubbd-version:
    description: The latest DUBBD package version
    value: ${{ steps.latest-dubbd-version.outputs.latest-dubbd-version }}

runs:
  using: composite
  steps:
    - id: latest-dubbd-version
      shell: bash
      run: |
        #!/bin/bash

        github_token="${{ inputs.github-token }}"

        package_name="${{ inputs.package-name }}"

        # Check if the package name contains '/'
        if [[ "$package_name" =~ "/" ]]; then

            # Replace all '/' with '%2F' for URL encoding
            package_name="${package_name//\//%2F}"
        fi

        latest_dubbd_version="$(curl -s -H "Authorization: Bearer $github_token" \
            https://api.github.com/orgs/defenseunicorns/packages/container/${package_name}/versions \
            | jq -r '.[0].metadata.container.tags[0]')"

        echo "latest-dubbd-version=$(echo "$latest_dubbd_version")" >> $GITHUB_OUTPUT