log-level: info
architecture: amd64
package:
  create:
    max_package_size: "1000000000"
    set:
      # renovate: datasource=gitlab-tags depName=big-bang/bigbang versioning=semver registryUrl=https://repo1.dso.mil
      bigbang_version: "2.7.1"
      # should line up with the flux version in the BB release, see https://repo1.dso.mil/big-bang/bigbang/-/blob/master/base/flux/gotk-components.yaml#L3
      flux_version: "2.0.1"
  deploy:
    set:
      # -- Domain name for the EKS cluster
      domain: bigbang.dev
      # -- TLS key
      key_file: bigbang.dev.key
      # -- TLS cert
      cert_file: bigbang.dev.cert
      # -- k3d host path
      host_path: "/var/lib/rancher/k3s/storage/*"
