name: Test EKS

on:
  workflow_call:
  pull_request:
    branches:
      - main
    paths:
      - "aws/eks/**"
      - "!*.md"

permissions:
  id-token: write
  contents: read

jobs:
  test-loki-bucket-tf:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: aws/eks/test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          role-duration-seconds: 21600

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'aws/loki/test/go.mod'

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2

      - name: Run Loki Tests
        env:

        run: |
          go test -timeout 40m -json -v . 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Upload test log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error