name: CI DUBBD k3d

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**.md"
      - "**.json"
      - "aws/**"
      - ".github/workflows/**aws**.y*ml"

jobs:
  test-release:
    uses: ./.github/workflows/test-k3d-package.yaml
    secrets: inherit
