name: CI DUBBD k3d

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**/*.md"
      - "**/*.json"
      - "**/*.png"
      - "**/*.svg"
      - "aws/**"
      - "oscal-component.y*ml"
      - ".github/workflows/*aws*.y*ml"
      - ".github/workflows/*cloudtrail*.y*ml"
      - ".github/workflows/*uds*.y*ml"
      - "**/*oscal-component.y*aml"

jobs:
  test-release:
    uses: ./.github/workflows/test-k3d-package.yaml
    secrets: inherit
