name: CI DUBBD k3d

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**.md"
      - "**.json"
      - "**.png"
      - "**.svg"
      - "aws/**"
      - ".github/workflows/ci-on-pull-request-aws.y*ml"
      - ".github/workflows/test-aws-package.y*ml"
      - ".github/workflows/test-aws-upgrade.y*ml"

jobs:
  test-release:
    uses: ./.github/workflows/test-k3d-package.yaml
    secrets: inherit
