name: CI DUBBD OSCAL

on:
#  pull_request:
#    branches:
#      - main
#    paths-ignore:
#      - ".gitignore"
#      - "LICENSE"
#      - "**/*.md"
#      - "**/*.json"
#      - "**/*.png"
#      - "**/*.svg"
#      - "k3d/**"
#      - ".github/workflows/*k3d*.y*ml"

  workflow_call:

jobs:
  test-release-oscal:
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/create-uds-oscal-component.yaml
    secrets: inherit
