name: CI DUBBD AWS

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**/*.md"
      - "**/*.json"
      - "**/*.png"
      - "**/*.svg"
      - "k3d/**"
      - "rke2/**"
      # - "oscal-component.y*ml"
      # -  aws/dubbd-aws/oscal-component.y*ml
      - "**/oscal-component.y*ml"
      - ".github/workflows/*k3d*.y*ml"
      - ".github/workflows/*rke2*.y*ml"
      - ".github/workflows/*infra*.y*ml"
      - ".github/test-infra/rke2/**"
      - ".github/workflows/oscal/*oscal-component.y*ml"

  workflow_call:

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint . -c .yamllint --no-warnings

  test-release:
    permissions:
      id-token: write
      contents: read
    needs: yaml-lint
    if: needs.yaml-lint.result == 'success' || needs.yaml-lint.result == 'skipped'
    uses: ./.github/workflows/test-dubbd-aws-install.yaml
    secrets: inherit

  test-upgrade:
    permissions:
      id-token: write
      contents: read
    needs: yaml-lint
    if: needs.yaml-lint.result == 'success' || needs.yaml-lint.result == 'skipped'
    uses: ./.github/workflows/test-dubbd-aws-upgrade.yaml
    secrets: inherit
