name: CI DUBBD AWS

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**/*.md"
      - "**/*.json"
      - "**/*.png"
      - "**/*.svg"
      - "aws/uds-core-aws/**"
      - "aws/cloudtrail/**"
      - "k3d/**"
      # - "oscal-component.y*ml"
      # -  aws/dubbd-aws/oscal-component.y*ml
      # -  aws/uds-core-aws/oscal-component.y*ml
      - "**/oscal-component.y*ml"
      - ".github/workflows/*k3d*.y*ml"
      - ".github/workflows/*cloudtrail*.y*ml"
      - ".github/workflows/*uds*.y*ml"
      - ".github/workflows/oscal/*oscal-component.y*ml"

  workflow_call:

jobs:
    test-release:
        uses: ./.github/workflows/test-dubbd-aws-install.yaml
        secrets: inherit

    test-upgrade:
        uses: ./.github/workflows/test-dubbd-aws-upgrade.yaml
        secrets: inherit
