name: CI DUBBD RKE2

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "**/*.md"
      - "**/*.json"
      - "**/*.png"
      - "**/*.svg"
      - "aws/**"
      - "k3d/**"
      - "oscal-component.y*ml"
      - ".github/workflows/*aws*.y*ml"
      - ".github/workflows/*k3d*.y*ml"
      - ".github/workflows/*infra*.y*ml"
      - ".github/test-infra/ci-dubbd-iac-aws/**"
      - ".github/test-infra/eks/**"
      - "**/*oscal-component.y*aml"

jobs:
  yaml-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files
        run: yamllint . -c .yamllint --no-warnings
  test-release:
    needs: yaml-lint
    if: needs.yaml-lint.result == 'success' || needs.yaml-lint.result == 'skipped'
    uses: ./.github/workflows/test-dubbd-rke2-install.yaml
    secrets: inherit
