name: CI DUBBD AWS

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
    test-release:
        uses: ./.github/workflows/test-aws-package.yaml
        secrets: inherit

    test-upgrade:
        uses: ./.github/workflows/test-aws-upgrade.yaml
        secrets: inherit
