name: CI DUBBD AWS

on:
  push:
    branches:
      - alt-velero-to-s3
  # pull_request:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - ".gitignore"
  #     - "LICENSE"
  #     - "**.md"
  #     - "**.json"
  #     - "aws/uds-core-aws/**"
  #     - "k3d/**"
  #     - ".github/workflows/**k3d**.y*ml"
  workflow_call:

jobs:
    test-release:
        uses: ./.github/workflows/test-dubbd-aws-install.yaml
        secrets: inherit

    test-upgrade:
        uses: ./.github/workflows/test-dubbd-aws-upgrade.yaml
        secrets: inherit
