name: Create Compliance MD Images

on:
  workflow_call:

permissions:
  id-token: write
  contents: write

jobs:
  create-and-update-compliance-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Setup Environment
        run: |
          npm install jsdom
          npm install js-yaml
          npm install d3

      - name: Download Javascript Image generator
        run: |
          git clone -b "0.0.1" --single-branch https://github.com/defenseunicorns/compliance-md-generator.git
          cd compliance-md-generator/
          node generatePieChartSvg.js
          cp -R compliance-images/* ../compliance-images/
          cd ..

      - name: Clean Up
        run: |
          rm -rf compliance-md-generator
          rm -rf node_modules
          rm package-lock.json
          rm package.json

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_checkout: true
