name: Create and Update DUBBD OSCAL

on:
  workflow_call:

permissions:
  id-token: write
  contents: write

jobs:
  create-and-update-dubbd-oscal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          ref: ${{ github.head_ref }}

      - name: Uses Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: "1.20"

      - name: Node and NPM
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: latest

      - name: Download Component Generator
        run: |
          git clone https://github.com/defenseunicorns/component-generator.git
          cd component-generator/
          make build
          cd ..

      - name: Create DUBBD OSCAL-Component File
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-oscal-component.yaml

      - name: Create DUBBD AWS OSCAL-Component File
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-aws-oscal-component.yaml

      - name: Create DUBBD RKE2 OSCAL-Component File
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-rke2-oscal-component.yaml

      - name: Clean Up
        run: rm -rf component-generator

      - name: Yaml Formatter and Cleanup
        run: |
          npm install --save-dev --save-exact prettier
          npx prettier defense-unicorns-distro/oscal-component.yaml aws/dubbd-aws/oscal-component.yaml rke2/oscal-component.yaml --write
          npm uninstall --save-dev prettier
          rm -rf node_modules/
          rm package.json
          rm package-lock.json

      - name: Lula Setup
        uses: defenseunicorns/lula-action/setup@095636b7880051e11b05f10a582fdd911526161c # Commit Tag

      - name: Lula Lint DUBBD
        uses: defenseunicorns/lula-action/lint@095636b7880051e11b05f10a582fdd911526161c # Commit Tag
        with:
          oscal-target: "defense-unicorns-distro/oscal-component.yaml"

      - name: Lula Lint AWS DUBBD
        uses: defenseunicorns/lula-action/lint@095636b7880051e11b05f10a582fdd911526161c # Commit Tag
        with:
          oscal-target: "aws/dubbd-aws/oscal-component.yaml"

      - name: Lula Lint AWS DUBBD - Velero
        uses: defenseunicorns/lula-action/lint@095636b7880051e11b05f10a582fdd911526161c # Commit Tag
        with:
          oscal-target: "aws/dubbd-aws/velero-oscal-component.yaml"

      - name: Lula Lint RKE2
        uses: defenseunicorns/lula-action/lint@095636b7880051e11b05f10a582fdd911526161c # Commit Tag
        with:
          oscal-target: "rke2/oscal-component.yaml"

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          skip_checkout: true
