name: DUBBD

on:
  pull_request:
    branches:
      - NEVER

permissions:
  id-token: write
  contents: read

jobs:
  eksctl:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          role-duration-seconds: 21600

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.28.3
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
    
      - name: Set eks_cluster_name
        id: get_cluster_name
        env:
          SHA: ${{ github.sha }}
        run: |
          echo "short_sha=${SHA:0:7}" >> $GITHUB_OUTPUT

      - name: Package EKSCTL 
        run: zarf package create --confirm
        working-directory: .github/workflows/eks

      - name: Create EKS cluster
        run: |
          echo ${{ steps.get_cluster_name.outputs.short_sha }}
          zarf package deploy zarf-package-distro-eks-multi.tar.zst --set cluster_name=${{ steps.get_cluster_name.outputs.short_sha }} --confirm 
        working-directory: .github/workflows/eks
        # eventually have zarf deploy   \
      - name: Show Cluster
        run: |
          kubectl get nodes

      - name: Zarf init
        run: |
          zarf init -a amd64 --components=git-server --confirm

      - name: Create DUBBD
        run: zarf package create --confirm
        working-directory: defense-unicorns-distro
        timeout-minutes: 60
      
      - name: Deploy DUBBD
        run: zarf package deploy zarf-package-*.tar.zst --confirm
        working-directory: defense-unicorns-distro
        timeout-minutes: 60

      - name: Remove DUBBD
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: defense-unicorns-distro
        timeout-minutes: 60

      - name: Teardown EKS cluster
        if: always()
        # can't do a zarf package remove since there's no kubernetes cluster.
        run: |
          ./eksctl delete cluster -f config.yaml --disable-nodegroup-eviction --wait
        working-directory: .github/workflows/eks

