name: DUBBD

on:
  pull_request:
    branches:
      - main

jobs:
  test-dubbd:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup AWS credentials, Install Zarf, Login to Registry1
        uses: ./.github/workflows/reusable-workflow.yml
    
      - name: Package EKSCTL 
        run: zarf package create --confirm
        working-directory: .github/workflows/eks

      - name: Create EKS cluster
        run: zarf package deploy zarf-package-distro-eks-multi.tar.zst --confirm --set cluster_name=${GITHUB_SHA:0:7}
        working-directory: .github/workflows/eks
        # eventually have zarf deploy   \
      - name: Show Cluster
        run: |
          kubectl get nodes

      - name: Zarf init
        run: |
          zarf init -a amd64 --components=git-server --confirm

      - name: Create DUBBD
        run: zarf package create --confirm
        working-directory: defense-unicorns-distro
        timeout-minutes: 60
      
      - name: Deploy DUBBD
        run: zarf package deploy zarf-package-*.tar.zst --confirm -l debug
        working-directory: defense-unicorns-distro
        timeout-minutes: 60

      - name: Remove DUBBD
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: defense-unicorns-distro
        timeout-minutes: 60

      - name: Teardown EKS cluster
        if: always()
        # can't do a zarf package remove since there's no kubernetes cluster.
        run: |
          ./eksctl delete cluster -f config.yaml --disable-nodegroup-eviction --wait
        working-directory: .github/workflows/eks
