name: Publish DUBBD Package

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Free GH runner space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Terraform version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - name: Create DUBBD Package
        uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: ${{ inputs.working_dir }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Zarf Package
        run: zarf package publish zarf-package-*.tar.zst oci://ghcr.io/defenseunicorns/packages
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60

      - name: Publish Zarf Skeleton
        run: zarf package publish . oci://ghcr.io/defenseunicorns/packages
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60
