name: Publish Dubbd

# Will remove before merge and make it only tags
on:
  workflow_call:
    inputs:
      release_created:
        required: false
        type: boolean
      working_dir:
        required: true
        type: string
      package_name:
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  publish-package:
    if: ${{ inputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.27.0
          download-init-package: true

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: dummy
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Zarf Package
        run: zarf package create --confirm
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60
      
      - name: Publish Zarf Package
        run: zarf package publish ${{ inputs.package_name }}-*.tar.zst oci://ghcr.io/defenseunicorns/packages
        working-directory: ${{ inputs.working_dir }}
        timeout-minutes: 60
