---
name: Slack Notification on Version Release

on:
  pull_request:
    branches:
      - faux-main-you-can-delete-me
# push:
#   branches:
#     - faux-main-you-can-delete-me
#   tags:
#     - test-tag

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: New version released
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'uds-new-release'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":mega: DUBBD ${{ github.ref}} is published! <version> <release notes body> "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
