name: Slack Notification on Version Release

on:
  push:
    branches:
      - faux-main-you-can-delete-me
      - slack-message-on-new-version-III

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: New version released
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: get_release
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_tag=$(echo "$release_json" | jq -r '.tag_name')
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

          release_body=$(echo "$release_json" | jq -r '.body')
          release_body="$(echo "$release_body" | sed -z 's/\n/\\n/g')"
          echo "RELEASE_BODY=$release_body" >> $GITHUB_ENV
          echo "---"
          echo $release_body

      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'uds-new-release'
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":mega: DUBBD ${{ env.RELEASE_TAG }} is published!",
                    "emoji": true
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "## [0.6.0](https://github.com/defenseunicorns/uds-package-dubbd/compare/v0.5.2...v0.6.0) (2023-08-03)\n\n\n### Features\n\n* improve neuvector config setup across distros ([#442](https://github.com/defenseunicorns/uds-package-dubbd/issues/442)) ([770d1e0](https://github.com/defenseunicorns/uds-package-dubbd/commit/770d1e0a66e1fd7ca6c0401e8b366aa099d61996))\n* initial oscal componenet ([#446](https://github.com/defenseunicorns/uds-package-dubbd/issues/446)) ([7d0dced](https://github.com/defenseunicorns/uds-package-dubbd/commit/7d0dced367d4103b608e5c2c745436d5dcb6e7c0))\n\n\n### Bug Fixes\n\n* add monitoring resources to zarf.yaml ([#462](https://github.com/defenseunicorns/uds-package-dubbd/issues/462)) ([425d343](https://github.com/defenseunicorns/uds-package-dubbd/commit/425d3436009df6843d2ee8ef2a1d537ffed12fc0))\n* avoid conflicts with BB authservice package ([#453](https://github.com/defenseunicorns/uds-package-dubbd/issues/453)) ([6c00497](https://github.com/defenseunicorns/uds-package-dubbd/commit/6c00497870b7bed3ce1b03554705b20dda746c41))\n* **deps:** update module github.com/aws/aws-sdk-go to v1.44.309 ([#443](https://github.com/defenseunicorns/uds-package-dubbd/issues/443)) ([c71faf7](https://github.com/defenseunicorns/uds-package-dubbd/commit/c71faf789fc771eeb0053618201f284ecee09537))\n* **deps:** update module github.com/aws/aws-sdk-go to v1.44.313 ([#456](https://github.com/defenseunicorns/uds-package-dubbd/issues/456)) ([cfb5140](https://github.com/defenseunicorns/uds-package-dubbd/commit/cfb5140cb3cf379707287829a30d01609d249908))\n* **deps:** update module github.com/aws/aws-sdk-go to v1.44.315 ([#464](https://github.com/defenseunicorns/uds-package-dubbd/issues/464)) ([c9c2ea3](https://github.com/defenseunicorns/uds-package-dubbd/commit/c9c2ea3da2994ad30732c83dda8975529b6af151))\n* **deps:** update module github.com/gruntwork-io/terratest to v0.43.11 ([#444](https://github.com/defenseunicorns/uds-package-dubbd/issues/444)) ([8fd6dcf](https://github.com/defenseunicorns/uds-package-dubbd/commit/8fd6dcfd9df678f33483019dce49f8a41a2b748f))\n* updating oscal configs to include neuvector ([#458](https://github.com/defenseunicorns/uds-package-dubbd/issues/458)) ([c0060cc](https://github.com/defenseunicorns/uds-package-dubbd/commit/c0060cc43e26a329a12046170abbe4bc72c8e813))\n\n\n### Miscellaneous\n\n* **deps:** update gitlab tag big-bang/bigbang to v2.7.0 ([#459](https://github.com/defenseunicorns/uds-package-dubbd/issues/459)) ([46c01d9](https://github.com/defenseunicorns/uds-package-dubbd/commit/46c01d9716f3294e337b1ebc54f984efd669f5ef))\n* **deps:** update gitlab tag big-bang/bigbang to v2.7.1 ([#461](https://github.com/defenseunicorns/uds-package-dubbd/issues/461)) ([b3b9fd6](https://github.com/defenseunicorns/uds-package-dubbd/commit/b3b9fd6b9728ac3efd211069cabc1a0eea7714e1))\n* release 0.5.3 ([#468](https://github.com/defenseunicorns/uds-package-dubbd/issues/468)) ([b4c61aa](https://github.com/defenseunicorns/uds-package-dubbd/commit/"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK


