name: Slack Notification on Version Release

on:
  workflow_call:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: New version released
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Latest Release
        id: get_release
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_tag=$(echo "$release_json" | jq -r '.tag_name')
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

          release_html_url=$(echo "$release_json" | jq -r '.html_url')
          echo "RELEASE_HTML_URL=$release_html_url" >> $GITHUB_ENV
          echo "---"
          echo $release_html_url

      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'uds-new-release'
          payload: |
            {
              "blocks": [
               {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":mega: *DUBBD <${{ env.RELEASE_HTML_URL }}|${{ env.RELEASE_TAG }}> has been released!* :mega:"
            			}
            		}
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
