name: Slack Notification on Version Release

on:
  push:
    branches:
      - slack-bot-message-on-new-release

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: New version released
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Latest Release
        id: get_release
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_tag=$(echo "$release_json" | jq -r '.tag_name')
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

          release_html_url=$(echo "$release_json" | jq -r '.html_url')
          echo "RELEASE_HTML_URL=$release_html_url" >> $GITHUB_ENV

          release_body=$(echo "$release_json" | jq -r '.body')
          release_body="$(echo "$release_body" | sed -z 's/\n/\\n/g')"
          echo "RELEASE_BODY=$release_body" >> $GITHUB_ENV

          echo "---"
          echo $release_html_url

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'C05CYSCMRNV'
          # For posting a simple plain text message
          payload: |
            {
              "unfurl_links": true,
              "blocks": [
               {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":mega: *DUBBD <${{ env.RELEASE_HTML_URL }}|${{ env.RELEASE_TAG }}> has been released!* :mega:"
            			}
            		}
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - uses: slackapi/slack-github-action@v1.24.0
        with:
          # Unlike the step posting a new message, this step does not accept a channel name.
          # Please use a channel ID, not a name here.
          channel-id: "C05CYSCMRNV"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "unfurl_links": true
              "blocks": [
               {
            			"type": "section",
            			"text": {
            				"type": "mrkdwn",
            				"text": ":mega: *DUBBD <${{ env.RELEASE_HTML_URL }}|${{ env.RELEASE_TAG }}> has been released!* :mega:"
            			}
            		}
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

#     - name: Send Slack notification
#       id: slack
#       uses: slackapi/slack-github-action@v1.24.0
#       with:
#         channel-id: 'uds-new-release'
#         payload: |
#           {
#             "blocks": [
#              {
#           			"type": "section",
#           			"text": {
#           				"type": "mrkdwn",
#           				"text": ":mega: *DUBBD <${{ env.RELEASE_HTML_URL }}|${{ env.RELEASE_TAG }}> has been released!* :mega:"
#           			}
#           		}
#             ]
#           }
#       env:
#         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
#         SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
