---
name: Slack Notification on Version Release

on:
# release:
#   types: [published]

  push:
    branches:
      - faux-main-you-can-delete-me
      - slack-message-on-new-version
#   tags:
#     - v0.0.6

jobs:
  send-notification:
    runs-on: ubuntu-latest
    name: New version released
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Release
        id: get_release
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_tag=$(echo "$release_json" | jq -r '.tag_name')
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV

      - name: Get Latest Release Body
        id: get_body
        run: |
          release_json=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          release_body=$(echo "$release_json" | jq -r '.body')
          echo "RELEASE_BODY=$release_BODY" >> $GITHUB_ENV



      - name: Send Slack notification
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: 'uds-new-release'
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":mega: DUBBD ${{ env.RELEASE_TAG }} is published! ",
                    "emoji": true

                  }
                },
            		{
            			"type": "divider"
            		},
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.RELEASE_TAG }} this will be the body \n is published! "
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
