name: Lint Terraform

on:
  workflow_call:
    inputs:
      path:
        type: string
        description: "The name of the path to test"
        required: true

jobs:
  tflint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/test-infra/${{ inputs.path }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform init
        run: terraform init -reconfigure -backend=false

      - name: terraform validate
        run: terraform validate

      - name: terraform fmt
        run: terraform fmt -recursive

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.46.1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        env:
          # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
          GITHUB_TOKEN: ${{ github.token }}

      - name: Run TFLint
        run: tflint -f compact --recursive

  tfsec-scan:
    needs: [tflint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ github.token }}
          soft_fail: true
          working-directory: .github/test-infra/${{ inputs.path }}

  regula:
    needs: [tflint]
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: List Directories
        run: ls -lsa

      - name: Scan with Regula
        uses: fugue/regula-action@v3.2.1
        with:
          input_path: .github/test-infra/${{ inputs.path }}
          input_type: tf
          severity: high
