name: Test DUBBD RKE2 Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - name: Free GH runner space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          role-session-name: ${{ github.job || github.event.client_payload.pull_request.head.sha || github.sha }}
          aws-region: us-west-2
          role-duration-seconds: 21600

      - name: Set Terraform version
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.7"

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: rke2
          download-init-package: true
          timeout-minutes: 60

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: rke2/test-deps/minio
          download-init-package: true
          timeout-minutes: 60

      - name: Create RKE2 cluster
        env:
          SHA: ${{ github.sha }}
        run: |
          terraform init -force-copy -upgrade \
            -backend-config="bucket=uds-ci-state-bucket" \
            -backend-config="key=tfstate/ci/install/${SHA:0:7}-rke2.tfstate" \
            -backend-config="region=us-west-2" \
            -backend-config="dynamodb_table=uds-ci-state-dynamodb"
          terraform plan
          sleep 15 # time to review
          terraform apply -auto-approve
          kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.21"
          kubectl apply -f storage-class.yaml
        working-directory: .github/test-infra/rke2

      - name: Zarf init
        run: zarf init -a amd64 --components=git-server --confirm

      - name: Deploy minio on RKE2 cluster
        run: zarf package deploy zarf-package-*.tar.zst
        working-directory: rke2/test-deps/minio
        timeout-minutes: 60

      - name: Deploy DUBBD on RKE2 cluster
        run: |
          zarf package deploy zarf-package-*.tar.zst \
          --confirm \
          --set VELERO_BUCKET=minio.minio.svc.cluster.local:9000/velero \
          --set VELERO_BUCKET_REGION=us-west-2 \
          --set VELERO_BUCKET_KEY=admin \
          --set VELERO_BUCKET_KEY_SECRET=changeme
        working-directory: rke2
        timeout-minutes: 60

      - name: Remove DUBBD from RKE2 cluster
        if: always()
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: rke2
        timeout-minutes: 60

      - name: Remove Zarf from RKE2 cluster
        if: always()
        run: zarf destroy --confirm
        timeout-minutes: 60

      - name: Teardown RKE2 cluster
        if: always()
        run: terraform destroy -auto-approve
        working-directory: .github/test-infra/rke2
