name: Test DUBBD k3d Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: dubbd-ubuntu-16-core-64-gb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: k3d
          download-init-package: true
          timeout-minutes: 60

      - name: Install k3d
        shell: bash
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.6.0 bash

      - name: Create k3d cluster
        run: zarf package deploy oci://ghcr.io/defenseunicorns/packages/uds-k3d:0.1.12-multi --confirm
        timeout-minutes: 60

      - name: Zarf Init
        run: zarf init --components=git-server --confirm
        timeout-minutes: 60

      - name: Deploy DUBBD on k3d cluster
        run: zarf package deploy zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Remove DUBBD from k3d cluster
        if: always()
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60
