name: Test DUBBD k3d Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: dubbd-ubuntu-16-core-64-gb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Test k3d package
        working-directory: k3d
        run: uds run test-k3d-pkg
