name: Test DUBBD OSCAL

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Uses Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Download Component Generator
        run: |
          git clone https://github.com/defenseunicorns/component-generator.git
          cd component-generator/
          make build
          cd ..

      - name: Create DUBBD OSCAL-Componenet File
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-oscal-component.yaml
       
      - name: Create DUBBD AWS OSCAL-Component File  
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-aws-oscal-component.yaml
      
      - name: Create UDS Core AWS OSCAL-Component File  
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-uds-core-aws-oscal-component.yaml
