name: Test DUBBD k3d Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: dubbd-ubuntu-16-core-64-gb
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Login to Registry1
        uses: docker/login-action@v3
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}

      - name: Create k3d pkg
        working-directory: k3d
        run: uds run create-k3d-pkg --no-progress

      - name: Create k3d cluster
        working-directory: k3d
        run: uds run setup-cluster --no-progress

      - name: Deploy k3d pkg
        working-directory: k3d
        run: uds run deploy-k3d-pkg --no-progress

      - name: Output debug info
        if: always()
        working-directory: k3d
        run: |
          uds zarf tools kubectl describe nodes
          uds zarf tools kubectl get events -A --sort-by='.lastTimestamp'
          uds zarf tools kubectl logs -n promtail daemonset.apps/promtail-promtail --all-containers

      - name: Remove k3d pkg
        working-directory: k3d
        run: uds run remove-k3d-pkg --no-progress
        continue-on-error: true
