name: Test DUBBD OSCAL

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Uses Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Download Component Generator
        run: |
          git clone https://github.com/defenseunicorns/component-generator.git
          cd component-generator/
          make build
          cd ..

      - name: Create DUBBD OSCAL-Componenet File
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-oscal-component.yaml
       
      - name: Create DUBBD AWS OSCAL-Component File  
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-dubbd-aws-oscal-component.yaml
      
      - name: Create UDS Core AWS OSCAL-Component File  
        run: ./component-generator/bin/component-generator aggregate --input .github/workflows/oscal/config-uds-core-aws-oscal-component.yaml
      
      - name: Clean Up
        run: rm -rf component-generator

      - name: Commit OSCAL-Component Files
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "GitHub Actions"
          git add oscal-component.yaml aws/dubbd-aws/oscal-component.yaml aws/uds-core-aws/oscal-component.yaml
          git commit -m "Add OSCAL"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
