name: Test DUBBD AWS Package

on:
  push:

permissions:
  id-token: write
  contents: read
  repository-projects: read
      
jobs:
  test-clean-k3d-install:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3


      - uses: ./.github/actions/create-bb-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: k3d
          download-init-package: true        
          timeout-minutes: 60

      - name: create_cluster
        uses: defenseunicorns/uds-aws-ci-k3d@action
        with:
          cluster_action: create
          aws_assume_role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}

      - name: Show Cluster
        run: |
          kubectl get nodes
          kubectl config get-contexts

      - name: Zarf init
        run: |
          zarf init -a amd64 --components=git-server --confirm

      - name: Deploy DUBBD-K3D
        env:
          SHA: ${{ github.sha }}
        run: |
          zarf package deploy zarf-package-*.tar.zst \
            --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Remove DUBBD-K3D
        if: always()
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: destroy_cluster
        if: always()
        uses: defenseunicorns/uds-aws-ci-k3d@action
        with:
          cluster_action: destroy
          aws_assume_role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}