name: CI DUBBD AWS

on:
  schedule:
    # run at midnight EST
    - cron: '0 4 * * *'
  pull_request:
    branches:
      - main
    paths:
      - 'aws/zarf.yaml'
      - 'aws/zarf-config.yaml'
      - 'aws/values/**'
  workflow_call:

jobs:
    test-release:
        uses: ./.github/workflows/test-aws-package.yaml
        secrets: inherit

    test-upgrade:
        uses: ./.github/workflows/test-aws-upgrade.yaml
        secrets: inherit
