name: Test DUBBD k3d Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/actions/create-bb-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: k3d
          download-init-package: true
          timeout-minutes: 60

      - name: Create k3d cluster
        id: create-cluster
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.2
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          aws-region: us-west-2

      - name: Zarf init
        run: zarf init -a amd64 --components=git-server --confirm

      - name: Deploy DUBBD on k3d cluster
        run: zarf package deploy zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Remove DUBBD from k3d cluster
        if: always()
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Teardown k3d cluster
        if: always()
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.2
        with:
          cluster-action: destroy
