name: Test DUBBD k3d Package

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-clean-install:
    runs-on: dubbd-ubuntu-8-core-32-gb
    steps:
      - name: Free GH runner space
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/create-zarf-package
        with:
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}
          working-dir: k3d
          download-init-package: true
          timeout-minutes: 60

      - name: Deploy DUBBD on k3d cluster
        run: zarf package deploy zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Remove DUBBD from k3d cluster
        if: always()
        run: zarf package remove zarf-package-*.tar.zst --confirm
        working-directory: k3d
        timeout-minutes: 60

      - name: Teardown k3d cluster
        if: always()
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@v0.0.3
        with:
          cluster-action: destroy
