variables:
  - name: VERSION
    description: "The version of the packages to deploy"
    # x-release-please-start-version
    default: "0.6.0"
    # x-release-please-end

tasks:
  - name: dubbd-k3d-pkg
    actions:
      - description: "Deploy the requested Zarf Package"
        cmd: |
          set -e
          zarf package deploy zart-package-dubbd-k3d-*.tar.zst --confirm
