tasks:
  - name: k3d-test-cluster
    actions:
      - description: "Create the K3d cluster"
        # renovate: datasource=github-tags depName=defenseunicorns/uds-k3d versioning=semver
        cmd: "zarf package deploy oci://defenseunicorns/uds-k3d:0.7.0 --set=K3D_IMAGE=rancher/k3s:v1.29.6-k3s1 --confirm --no-progress"

      - description: "Initialize the cluster with Zarf"
        # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
        cmd: "zarf package deploy oci://defenseunicorns/init:v0.38.3 --confirm --components=git-server --no-progress"
